from generators.common import hex_to_rgb


def _ansi_fg(hex_color: str) -> str:
    r, g, b = hex_to_rgb(hex_color)
    return f"\\[\\e[38;2;{r};{g};{b}m\\]"


def render(c: dict[str, str], source_path: str) -> str:
    accent_start_ansi = _ansi_fg(c["accent_start"])
    accent_end_ansi = _ansi_fg(c["accent_end"])
    text_ansi = _ansi_fg(c["text"])
    red_ansi = _ansi_fg(c["red"])
    reset_ansi = "\\[\\e[0m\\]"

    return f"""# Auto-generated by .config/theme/scripts/generate_theme.py
# Source: {source_path}
# Do not edit by hand; edit ~/.dotfiles/.config/theme/palette.json instead.

THEME_BASE="{c['base']}"
THEME_TERMINAL_BG="{c['terminal_bg']}"
THEME_TEXT_HEX="{c['text']}"
THEME_ACCENT_START_HEX="{c['accent_start']}"
THEME_ACCENT_END_HEX="{c['accent_end']}"
THEME_RED_HEX="{c['red']}"

THEME_TEXT="{text_ansi}"
THEME_ACCENT_START="{accent_start_ansi}"
THEME_ACCENT_END="{accent_end_ansi}"
THEME_RED="{red_ansi}"
THEME_RESET="{reset_ansi}"

# Backward-compatible aliases
GREEN="$THEME_ACCENT_START"
ORANGE="$THEME_ACCENT_END"
RESET="$THEME_RESET"
"""
