def _hex6(x: str) -> str:
    # foot expects RRGGBB without a leading '#'
    return x[1:] if x.startswith("#") else x


def render(c: dict[str, str], source_path: str) -> str:
    return f"""# Auto-generated by .config/theme/scripts/generate_theme.py
# Source: {source_path}
# Do not edit by hand; edit ~/.dotfiles/.config/theme/palette.json instead.

[colors-dark]
background={_hex6(c['terminal_bg'])}
foreground={_hex6(c['terminal_fg'])}

# Cursor is: <text> <cursor>
cursor={_hex6(c['terminal_bg'])} {_hex6(c['text'])}

selection-background={_hex6(c['selection_bg'])}
selection-foreground={_hex6(c['text'])}

urls={_hex6(c['accent_end'])}

# normal
regular0={_hex6(c['surface0'])}
regular1={_hex6(c['red'])}
regular2={_hex6(c['terminal_green'])}
regular3={_hex6(c['peach'])}
regular4={_hex6(c['accent_end'])}
regular5={_hex6(c['overlay1'])}
regular6={_hex6(c['terminal_cyan'])}
regular7={_hex6(c['text'])}

# bright
bright0={_hex6(c['surface1'])}
bright1={_hex6(c['red'])}
bright2={_hex6(c['terminal_green'])}
bright3={_hex6(c['peach'])}
bright4={_hex6(c['accent_end'])}
bright5={_hex6(c['overlay1'])}
bright6={_hex6(c['terminal_cyan'])}
bright7={_hex6(c['accent_text_right'])}
"""
