def _rgba(hex_color: str, alpha: str) -> str:
    return f"rgba({hex_color.lstrip('#')}{alpha})"


def render(c: dict[str, str], source_path: str) -> str:
    active_a = _rgba(c["accent_start"], "ff")
    active_b = _rgba(c["accent_end"], "ff")
    inactive = _rgba(c["overlay1"], "aa")
    return f"""# Auto-generated by .config/theme/scripts/generate_theme.py
# Source: {source_path}
# Do not edit by hand; edit ~/.dotfiles/.config/theme/palette.json instead.

# Focus borders
general:col.active_border = {active_a} {active_b} 45deg
general:col.inactive_border = {inactive}
"""
