def render(c: dict[str, str], source_path: str) -> str:
    return f"""# Auto-generated by .config/theme/scripts/generate_theme.py
# Source: {source_path}
# Do not edit by hand; edit ~/.dotfiles/.config/theme/palette.json instead.

background {c['terminal_bg']}
foreground {c['terminal_fg']}
selection_background {c['selection_bg']}
selection_foreground {c['text']}
url_color {c['accent_end']}
cursor {c['text']}
cursor_text_color {c['terminal_bg']}

# Tabs
active_tab_background {c['accent_end']}
active_tab_foreground {c['accent_text_right']}
inactive_tab_background {c['surface1']}
inactive_tab_foreground {c['overlay1']}

# Windows
active_border_color {c['accent_end']}
inactive_border_color {c['surface1']}

# normal
color0 {c['surface0']}
color1 {c['red']}
color2 {c['terminal_green']}
color3 {c['peach']}
color4 {c['accent_end']}
color5 {c['overlay1']}
color6 {c['terminal_cyan']}
color7 {c['text']}

# bright
color8 {c['surface1']}
color9 {c['red']}
color10 {c['terminal_green']}
color11 {c['peach']}
color12 {c['accent_end']}
color13 {c['overlay1']}
color14 {c['terminal_cyan']}
color15 {c['accent_text_right']}

# extended
color16 {c['peach']}
color17 {c['red']}
"""
