def render(c: dict[str, str], source_path: str) -> str:
    return f"""# Auto-generated by .config/theme/scripts/generate_theme.py
# Source: {source_path}
# Do not edit by hand; edit ~/.dotfiles/.config/theme/palette.json instead.

gui:
  theme:
    selectedLineBgColor:
      - '{c["selection_bg"]}'
"""
