def render(c: dict[str, str], source_path: str) -> str:
    return f"""-- Auto-generated by .config/theme/scripts/generate_theme.py
-- Source: {source_path}
-- Do not edit by hand; edit ~/.dotfiles/.config/theme/palette.json instead.

return {{
  green = "{c['accent_start']}",
  orange = "{c['accent_end']}",
  brown = "{c['surface1']}",
  violet = "{c['mantle']}",
  red = "{c['red']}",
  fg = "{c['text']}",
  bg = "{c['base']}",
  inactive_bg = "{c['surface0']}",
  semilightgray = "{c['overlay1']}",
}}
"""
