def render(c: dict[str, str], source_path: str) -> str:
    return f"""# Auto-generated by .config/theme/scripts/generate_theme.py
# Source: {source_path}

set -g status-position top
set -g status-style 'bg={c['base']},fg={c['text']}'
set -g message-style 'bg={c['accent_end']},fg={c['accent_text_right']}'
set -g message-command-style 'bg={c['accent_start']},fg={c['accent_text_left']}'
set -g mode-style 'bg={c['accent_end']},fg={c['accent_text_right']},bold'

set -g pane-border-style 'fg={c['surface1']}'
set -g pane-active-border-style 'fg={c['accent_end']}'
set -g pane-border-lines heavy
set -g pane-border-status top
set -g pane-border-format '#{{?pane_active,#[bg={c['accent_end']},fg={c['accent_text_right']},bold] ACTIVE #[default],#[fg={c['overlay1']}] pane }} #P '

set -g window-status-style 'bg={c['base']},fg={c['overlay1']}'
set -g window-status-current-style 'bg={c['accent_start']},fg={c['accent_text_left']},bold'
set -g window-status-format ' #I:#W '
set -g window-status-current-format ' #I:#W '
set -g window-status-separator ''

set -g status-left-length 32
set -g status-right-length 80
set -g status-left '#[bg={c['accent_start']},fg={c['accent_text_left']},bold] #S #[bg={c['base']},fg={c['accent_start']}]'
set -g status-right '#[bg={c['base']},fg={c['accent_end']}]#[bg={c['accent_end']},fg={c['accent_text_right']}] %Y-%m-%d %H:%M '

set -g clock-mode-colour '{c['accent_end']}'
"""
