from generators.common import hex_to_rgb, rgb_to_xterm_index


def render(c: dict[str, str], source_path: str) -> str:
    idx = {k: rgb_to_xterm_index(hex_to_rgb(v)) for k, v in c.items() if isinstance(v, str) and v.startswith("#")}
    bg = "default"
    return f"""" Auto-generated by .config/theme/scripts/generate_theme.py
" Source: {source_path}
" Do not edit by hand; edit ~/.dotfiles/.config/theme/palette.json instead.

highlight clear

highlight Win cterm=none ctermfg={idx['text']} ctermbg={bg}
highlight Directory cterm=bold ctermfg={idx['accent_end']} ctermbg=default
highlight Link cterm=bold ctermfg={idx['accent_start']} ctermbg=default
highlight BrokenLink cterm=bold ctermfg={idx['red']} ctermbg=default
highlight HardLink cterm=none ctermfg={idx['accent_end']} ctermbg=default
highlight Socket cterm=bold ctermfg={idx['mantle']} ctermbg=default
highlight Device cterm=bold ctermfg={idx['red']} ctermbg=default
highlight Fifo cterm=bold ctermfg={idx['accent_start']} ctermbg=default
highlight Executable cterm=bold ctermfg={idx['accent_start']} ctermbg=default
highlight Selected cterm=bold ctermfg={idx['text']} ctermbg={idx['surface0']}
highlight CurrLine cterm=bold,reverse ctermfg=default ctermbg=default
highlight TopLine cterm=none ctermfg={idx['text']} ctermbg={idx['surface1']}
highlight TopLineSel cterm=bold ctermfg={idx['text']} ctermbg={idx['surface0']}
highlight StatusLine cterm=bold ctermfg={idx['text']} ctermbg={idx['surface1']}
highlight WildMenu cterm=underline,reverse ctermfg={idx['text']} ctermbg={bg}
highlight CmdLine cterm=none ctermfg={idx['text']} ctermbg={bg}
highlight ErrorMsg cterm=none ctermfg={idx['red']} ctermbg={bg}
highlight Border cterm=none ctermfg={idx['overlay1']} ctermbg={bg}
highlight OtherLine ctermfg=default ctermbg=default
highlight JobLine cterm=bold,reverse ctermfg={idx['text']} ctermbg={bg}
highlight SuggestBox cterm=bold ctermfg=default ctermbg=default
highlight CmpMismatch cterm=bold ctermfg={idx['text']} ctermbg={idx['red']}
highlight CmpUnmatched cterm=bold ctermfg={idx['text']} ctermbg={idx['accent_start']}
highlight CmpBlank ctermfg=default ctermbg=default
highlight AuxWin ctermfg=default ctermbg=default
highlight TabLine cterm=none ctermfg={idx['text']} ctermbg={bg}
highlight TabLineSel cterm=bold,reverse ctermfg=default ctermbg=default
highlight User1 ctermfg=default ctermbg=default
highlight User2 ctermfg=default ctermbg=default
highlight User3 ctermfg=default ctermbg=default
highlight User4 ctermfg=default ctermbg=default
highlight User5 ctermfg=default ctermbg=default
highlight User6 ctermfg=default ctermbg=default
highlight User7 ctermfg=default ctermbg=default
highlight User8 ctermfg=default ctermbg=default
highlight User9 ctermfg=default ctermbg=default
highlight OtherWin ctermfg=default ctermbg=default
highlight LineNr ctermfg=default ctermbg=default
highlight OddLine ctermfg=default ctermbg=default
"""
