from generators.common import contrast_text, rotate_hue


def render(c: dict[str, str], source_path: str) -> str:
    dictation_recording = rotate_hue(c["accent_start"], 90, saturation_scale=1.12, lightness_scale=1.02)
    dictation_transcribing = rotate_hue(c["accent_end"], 210, saturation_scale=0.92, lightness_scale=1.04)
    dictation_recording_text = contrast_text(dictation_recording, dark=c["crust"], light=c["text"])
    dictation_transcribing_text = contrast_text(dictation_transcribing, dark=c["crust"], light=c["text"])

    return f"""/* Auto-generated by .config/theme/scripts/generate_theme.py */
/* Source: {source_path} */
@define-color base {c['base']};
@define-color mantle {c['mantle']};
@define-color crust {c['crust']};

@define-color text {c['text']};
@define-color surface0 {c['surface0']};
@define-color surface1 {c['surface1']};
@define-color overlay1 {c['overlay1']};
@define-color peach {c['peach']};

@define-color bar_grad_start {c['accent_start']};
@define-color bar_grad_end {c['accent_end']};
@define-color bar_text_left {c['accent_text_left']};
@define-color bar_text_mid {c['bar_text_mid']};
@define-color bar_text_right {c['accent_text_right']};
@define-color dictation_recording {dictation_recording};
@define-color dictation_recording_text {dictation_recording_text};
@define-color dictation_transcribing {dictation_transcribing};
@define-color dictation_transcribing_text {dictation_transcribing_text};
"""
