def render(c: dict[str, str], source_path: str) -> str:
    return f"""/* Auto-generated by .config/theme/scripts/generate_theme.py */
/* Source: {source_path} */
@define-color base {c['base']};
@define-color mantle {c['mantle']};
@define-color crust {c['crust']};

@define-color text {c['text']};
@define-color surface0 {c['surface0']};
@define-color surface1 {c['surface1']};
@define-color overlay1 {c['overlay1']};
@define-color peach {c['peach']};

@define-color bar_grad_start {c['accent_start']};
@define-color bar_grad_end {c['accent_end']};
@define-color bar_text_left {c['accent_text_left']};
@define-color bar_text_mid {c['bar_text_mid']};
@define-color bar_text_right {c['accent_text_right']};
"""
