-- Auto-generated by .config/theme/scripts/generate_theme.py
-- Source: /home/nicklas/.dotfiles/.config/theme/palette.json
-- Do not edit by hand; edit ~/.dotfiles/.config/theme/palette.json instead.

hl.config({
    general = {
        col = {
            active_border = {
                colors = { "rgba(5e81acff)", "rgba(88c0d0ff)" },
                angle = 45,
            },
            inactive_border = "rgba(7f8ea3aa)",
        },
    },
})
