#!/usr/bin/env python3
import json
import pathlib
import re
import sys


def main() -> int:
    home = pathlib.Path.home()
    palette_path = pathlib.Path(
        sys.argv[1] if len(sys.argv) > 1 else home / ".dotfiles/.config/theme/palette.json"
    )
    out_path = pathlib.Path(
        sys.argv[2]
        if len(sys.argv) > 2
        else home / ".dotfiles/.config/tmux/theme.generated.conf"
    )

    if not palette_path.is_file():
        print(f"ERROR: palette file not found: {palette_path}", file=sys.stderr)
        return 1

    required = [
        "base",
        "mantle",
        "crust",
        "text",
        "surface0",
        "surface1",
        "overlay1",
        "accent_start",
        "accent_end",
        "accent_text_left",
        "accent_text_right",
    ]

    with palette_path.open("r", encoding="utf-8") as f:
        palette = json.load(f)

    missing = [k for k in required if k not in palette]
    if missing:
        print(f"ERROR: missing palette keys: {', '.join(missing)}", file=sys.stderr)
        return 1

    hex_color = re.compile(r"^#[0-9a-fA-F]{6}$")
    for key in required:
        value = str(palette[key])
        if not hex_color.match(value):
            print(f"ERROR: invalid color for {key}: {value}", file=sys.stderr)
            return 1

    c = palette
    content = f"""# Auto-generated by .config/theme/scripts/generate_theme.py
# Source: {palette_path}

set -g status-position top
set -g status-style 'bg={c['base']},fg={c['text']}'
set -g message-style 'bg={c['accent_end']},fg={c['accent_text_right']}'
set -g message-command-style 'bg={c['accent_start']},fg={c['accent_text_left']}'
set -g mode-style 'bg={c['accent_end']},fg={c['accent_text_right']},bold'

set -g pane-border-style 'fg={c['surface1']}'
set -g pane-active-border-style 'fg={c['accent_end']}'
set -g pane-border-lines heavy
set -g pane-border-status top
set -g pane-border-format '#{{?pane_active,#[bg={c['accent_end']},fg={c['accent_text_right']},bold] ACTIVE #[default],#[fg={c['overlay1']}] pane }} #P '

set -g window-status-style 'bg={c['base']},fg={c['overlay1']}'
set -g window-status-current-style 'bg={c['accent_start']},fg={c['accent_text_left']},bold'
set -g window-status-format ' #I:#W '
set -g window-status-current-format ' #I:#W '
set -g window-status-separator ''

set -g status-left-length 32
set -g status-right-length 80
set -g status-left '#[bg={c['accent_start']},fg={c['accent_text_left']},bold] #S #[bg={c['base']},fg={c['accent_start']}]'
set -g status-right '#[bg={c['base']},fg={c['accent_end']}]#[bg={c['accent_end']},fg={c['accent_text_right']}] %Y-%m-%d %H:%M '

set -g clock-mode-colour '{c['accent_end']}'
"""

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    print(f"Generated {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
