#!/usr/bin/env python3
import json
import pathlib
import re
import sys


def generate_tmux(c: dict[str, str], palette_path: pathlib.Path) -> str:
    return f"""# Auto-generated by .config/theme/scripts/generate_theme.py
# Source: {palette_path}

set -g status-position top
set -g status-style 'bg={c['base']},fg={c['text']}'
set -g message-style 'bg={c['accent_end']},fg={c['accent_text_right']}'
set -g message-command-style 'bg={c['accent_start']},fg={c['accent_text_left']}'
set -g mode-style 'bg={c['accent_end']},fg={c['accent_text_right']},bold'

set -g pane-border-style 'fg={c['surface1']}'
set -g pane-active-border-style 'fg={c['accent_end']}'
set -g pane-border-lines heavy
set -g pane-border-status top
set -g pane-border-format '#{{?pane_active,#[bg={c['accent_end']},fg={c['accent_text_right']},bold] ACTIVE #[default],#[fg={c['overlay1']}] pane }} #P '

set -g window-status-style 'bg={c['base']},fg={c['overlay1']}'
set -g window-status-current-style 'bg={c['accent_start']},fg={c['accent_text_left']},bold'
set -g window-status-format ' #I:#W '
set -g window-status-current-format ' #I:#W '
set -g window-status-separator ''

set -g status-left-length 32
set -g status-right-length 80
set -g status-left '#[bg={c['accent_start']},fg={c['accent_text_left']},bold] #S #[bg={c['base']},fg={c['accent_start']}]'
set -g status-right '#[bg={c['base']},fg={c['accent_end']}]#[bg={c['accent_end']},fg={c['accent_text_right']}] %Y-%m-%d %H:%M '

set -g clock-mode-colour '{c['accent_end']}'
"""


def generate_waybar_colors(c: dict[str, str], palette_path: pathlib.Path) -> str:
    return f"""/* Auto-generated by .config/theme/scripts/generate_theme.py */
/* Source: {palette_path} */
@define-color base {c['base']};
@define-color mantle {c['mantle']};
@define-color crust {c['crust']};

@define-color text {c['text']};
@define-color surface0 {c['surface0']};
@define-color surface1 {c['surface1']};
@define-color overlay1 {c['overlay1']};
@define-color peach {c['peach']};

@define-color bar_grad_start {c['accent_start']};
@define-color bar_grad_end {c['accent_end']};
@define-color bar_text_left {c['accent_text_left']};
@define-color bar_text_mid {c['bar_text_mid']};
@define-color bar_text_right {c['accent_text_right']};
"""

def generate_nvim_palette(c: dict[str, str], palette_path: pathlib.Path) -> str:
    return f"""-- Auto-generated by .config/theme/scripts/generate_theme.py
-- Source: {palette_path}
-- Do not edit by hand; edit ~/.dotfiles/.config/theme/palette.json instead.

return {{
  green = "{c['accent_start']}",
  orange = "{c['accent_end']}",
  brown = "{c['surface1']}",
  violet = "{c['mantle']}",
  red = "{c['red']}",
  fg = "{c['text']}",
  bg = "{c['base']}",
  inactive_bg = "{c['surface0']}",
  semilightgray = "{c['overlay1']}",
}}
"""


def main() -> int:
    home = pathlib.Path.home()
    palette_path = pathlib.Path(
        sys.argv[1] if len(sys.argv) > 1 else home / ".dotfiles/.config/theme/palette.json"
    )
    tmux_out_path = pathlib.Path(
        sys.argv[2]
        if len(sys.argv) > 2
        else home / ".dotfiles/.config/tmux/theme.generated.conf"
    )
    waybar_out_path = home / ".dotfiles/.config/waybar/colors.generated.css"
    nvim_out_path = home / ".dotfiles/.config/nvim/lua/theme/generated_palette.lua"

    if not palette_path.is_file():
        print(f"ERROR: palette file not found: {palette_path}", file=sys.stderr)
        return 1

    required = [
        "base",
        "mantle",
        "crust",
        "text",
        "surface0",
        "surface1",
        "overlay1",
        "accent_start",
        "accent_end",
        "accent_text_left",
        "accent_text_right",
    ]

    with palette_path.open("r", encoding="utf-8") as f:
        palette = json.load(f)

    missing = [k for k in required if k not in palette]
    if missing:
        print(f"ERROR: missing palette keys: {', '.join(missing)}", file=sys.stderr)
        return 1

    palette.setdefault("peach", "#fab387")
    palette.setdefault("bar_text_mid", palette["text"])
    palette.setdefault("red", "#f38ba8")

    hex_color = re.compile(r"^#[0-9a-fA-F]{6}$")
    for key, value in palette.items():
        if isinstance(value, str) and key in required + ["peach", "bar_text_mid", "red"]:
            if not hex_color.match(value):
                print(f"ERROR: invalid color for {key}: {value}", file=sys.stderr)
                return 1

    tmux_out_path.parent.mkdir(parents=True, exist_ok=True)
    tmux_out_path.write_text(generate_tmux(palette, palette_path), encoding="utf-8")
    print(f"Generated {tmux_out_path}")

    waybar_out_path.parent.mkdir(parents=True, exist_ok=True)
    waybar_out_path.write_text(generate_waybar_colors(palette, palette_path), encoding="utf-8")
    print(f"Generated {waybar_out_path}")

    nvim_out_path.parent.mkdir(parents=True, exist_ok=True)
    nvim_out_path.write_text(generate_nvim_palette(palette, palette_path), encoding="utf-8")
    print(f"Generated {nvim_out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
