-- Auto-generated by .config/theme/scripts/generate_theme.py
-- Source: /home/nicklas/.dotfiles/.config/theme/palette.json
-- Do not edit by hand; edit ~/.dotfiles/.config/theme/palette.json instead.

return {
  green = "#5e81ac",
  orange = "#88c0d0",
  brown = "#3a4356",
  violet = "#7f8ea3",
  mantle = "#161a24",
  red = "#f38ba8",
  fg = "#d8dee9",
  bg = "#1b1f2a",
  inactive_bg = "#2a3140",
  semilightgray = "#7f8ea3",
}
