-- Auto-generated by .config/theme/scripts/generate_theme.py
-- Source: /home/nicklas/.dotfiles/.config/theme/palette.json
-- Do not edit by hand; edit ~/.dotfiles/.config/theme/palette.json instead.

return {
  green = "#6aa272",
  orange = "#8ccf95",
  brown = "#3f4a44",
  violet = "#1a201d",
  red = "#f38ba8",
  fg = "#d7e3da",
  bg = "#1f2522",
  inactive_bg = "#2f3833",
  semilightgray = "#8a9b90",
}
