-- Auto-generated by .config/theme/scripts/generate_theme.py
-- Source: /home/nicklas/.dotfiles/.config/theme/palette.json
-- Do not edit by hand; edit ~/.dotfiles/.config/theme/palette.json instead.

return {
  green = "#2f7f5f",
  orange = "#3fa7c9",
  brown = "#45475a",
  violet = "#181825",
  red = "#f38ba8",
  fg = "#cdd6f4",
  bg = "#1e1e2e",
  inactive_bg = "#313244",
  semilightgray = "#7f849c",
}
