#!/bin/sh
# Arguments:
# 1: color

col=${1:-#fff}

# Define array
ramp_arr=(▁ ▂ ▃ ▄ ▅ ▆ ▇ █)
printf "<span color='$col'>"
sar -n DEV 2 1 | grep -E 'Average:\s+[0-9]+' | while read -r line ; do
    #val=$(echo $line | awk '{cpu_usage=$3} END {printf "%0.2f", cpu_usage}')
    val=$(echo $line | awk '{printf "%0.2f", $3+$4}')
    #echo $val
    idx=`echo "scale=4; $val/14.3" | bc`
    intidx=$( printf "%.0f" $idx )
    printf "${ramp_arr[$intidx]}"
done
printf "</span>"
echo

